/************************************/
/*** Import des modules nécessaires */
const { DataTypes } = require('sequelize')

module.exports = (sequelize) => {
    const Condidat = sequelize.define('Condidat', {
        numcin:                 {type: DataTypes.STRING(30),    primaryKey: true, allowNull: false},
        nom:                    {type: DataTypes.INTEGER(30),   allowNull: true},
        prenom:                 {type: DataTypes.STRING(30),    allowNull: true},
        numCondidat:            {type: DataTypes.STRING(30),    allowNull: true},
        dateNaiss:              {type: DataTypes.DATE,          allowNull: true},
        lieuNaiss:              {type: DataTypes.STRING(30),    allowNull: true},
        sitFam:                 {type: DataTypes.STRING(1),     allowNull: true},
        Sexe:                   {type: DataTypes.STRING(1),     allowNull: true},
        taille:                 {type: DataTypes.DECIMAL(30,11),allowNull: true},
        poids:                  {type: DataTypes.DECIMAL(4,0),  allowNull: true},
        adresse:                {type: DataTypes.STRING(100),   allowNull: true},
        email:                  {type: DataTypes.STRING(30),    allowNull: true},
        groupe:                 {type: DataTypes.STRING(20),    allowNull: true},
        promotion:              {type: DataTypes.STRING(10),    allowNull: true},
        nationalite:            {type: DataTypes.STRING(30),    allowNull: true},
        dateDebutFor:           {type: DataTypes.DATE,          allowNull: true},
        dateFinFor:             {type: DataTypes.DATE,          allowNull: true},
        telFixe:                {type: DataTypes.STRING(10),    allowNull: true},
        tel1:                   {type: DataTypes.STRING(10),    allowNull: true},
        tel2:                   {type: DataTypes.STRING(10),    allowNull: true},
        telGsm3:                {type: DataTypes.STRING(10),    allowNull: true},
        nomPere:                {type: DataTypes.STRING(30),    allowNull: true},
        prenomPere:             {type: DataTypes.STRING(30),    allowNull: true},
        professionPere:         {type: DataTypes.STRING(30),    allowNull: true},
        telFixePere:            {type: DataTypes.STRING(30),    allowNull: true},
        telGsmPere:             {type: DataTypes.STRING(30),    allowNull: true},
        nomMere:                {type: DataTypes.STRING(30),    allowNull: true},
        prenomMere:             {type: DataTypes.STRING(30),    allowNull: true},
        professionMere:         {type: DataTypes.STRING(30),    allowNull: true},
        telFixeMere:            {type: DataTypes.STRING(30),    allowNull: true},
        telGsmMere:             {type: DataTypes.STRING(30),    allowNull: true},
        adresseParents:         {type: DataTypes.STRING(100),   allowNull: true},
        recrute1:               {type: DataTypes.STRING(1),     allowNull: true},
        date1:                  {type: DataTypes.DATE,          allowNull: true},
        recrute2:               {type: DataTypes.STRING(1),     allowNull: true},
        date2:                  {type: DataTypes.DATE,          allowNull: true},
        sitSvc:                 {type: DataTypes.STRING(20),    allowNull: true},
        dateSitSvc:             {type: DataTypes.DATE,          allowNull: true},
        refSitSvc:              {type: DataTypes.STRING(200),   allowNull: true},
        religion:               {type: DataTypes.STRING(25),    allowNull: true},
        sectione:               {type: DataTypes.STRING(25),    allowNull: true},
        nivFormation:           {type: DataTypes.STRING(25),    allowNull: true},
        passeport:              {type: DataTypes.STRING(15),    allowNull: true},
        dateDebutPass:          {type: DataTypes.DATE,          allowNull: true},
        dateFinPass:            {type: DataTypes.DATE,          allowNull: true},
        villePass:              {type: DataTypes.STRING(20),    allowNull: true},
        arabeParleeCourant:     {type: DataTypes.STRING(1),     allowNull: true},
        arabeParleeMoyen:       {type: DataTypes.STRING(1),     allowNull: true},
        arabeParleeMinimal:     {type: DataTypes.STRING(1),     allowNull: true},
        francaisParleeCourant:  {type: DataTypes.STRING(1),     allowNull: true},
        francaisParleeMoyen:    {type: DataTypes.STRING(1),     allowNull: true},
        francaisParleeMinimal:  {type: DataTypes.STRING(1),     allowNull: true},
        anglaisParleeCourant:   {type: DataTypes.STRING(1),     allowNull: true},
        anglaisParleeMoyen:     {type: DataTypes.STRING(1),     allowNull: true},
        anglaisParleeMinimal:   {type: DataTypes.STRING(1),     allowNull: true},
        arabeEcriteCourant:     {type: DataTypes.STRING(1),     allowNull: true},
        arabeEcriteMoyen:       {type: DataTypes.STRING(1),     allowNull: true},
        arabeEcriteinimal:      {type: DataTypes.STRING(1),     allowNull: true},
        francaisEcriteCourant:  {type: DataTypes.STRING(1),     allowNull: true},
        francaisEcriteMoyen:    {type: DataTypes.STRING(1),     allowNull: true},
        francaisEcriteMinimal:  {type: DataTypes.STRING(1),     allowNull: true},
        anglaisEcriteCourant:   {type: DataTypes.STRING(1),     allowNull: true},
        anglaisEcriteMoyen:     {type: DataTypes.STRING(1),     allowNull: true},
        anglaisEcriteMinimal:   {type: DataTypes.STRING(1),     allowNull: true},
        nivAnglais:             {type: DataTypes.STRING(30),    allowNull: true},
        nbrAvertissement:       {type: DataTypes.STRING(1),     allowNull: true},
        categ:                  {type: DataTypes.STRING(50),    allowNull: true},
        urlPhoto:               {type: DataTypes.STRING(50),    allowNull: true},


    }, { paranoid: true })           // Ici pour faire du softDelete
    return Condidat
}